### ISSUE TITLE
Add a new button plz!

### ISSUE THREAD

**Issue by SoraSushi776** [voosc/vtuber-voice-button-collection#4]
button url : https://77sun.sushi810.com.cn/
she is a vup from Taiwan, now streaming in Bilibili

**Comment by rakuaki** [comment]
Thank you for your issue. 
I'm very happy that you can notice our organization and projects. 
However, most of our projects have been archived or lack management. Only a small part is still working properly. This situation has been going on for several years. 
Due to the situation that I have mentioned above, I can't give a definitive answer as to when or if I can add your button to the collection website. 
However,  we still hope you can enjoy your project and the experience with your favorite vup. 
Wish you a good day.

**Comment by rakuaki** [comment]
Issue Closed

**Comment by blacktunes** [comment]
如果你能保证网站长期稳定访问我可以添加到合集里
但这其实是一个已经死去的项目，更多的只是作为纪念
